### ISSUE TITLE
needs special handling when installing to ROOT (under Tomcat)

### ISSUE THREAD

**Issue by kares** [killbill/killbill-cloud#2]
... or a control parameter whether to extract the .war

```
killbill:
  version: 0.12.1
  webapp_path: /var/lib/tomcat7/webapps/ROOT
  plugins_dir: /var/tmp/bundles
```

simply created a _killbill-xxx.war_ file under the ROOT directory (which is no a valid **/** deployment) instead of extracting the .war content there ... scenarios where the .war is renamed would likely be also interesting on some servers (have not tried) e.g. _/var/lib/tomcat7/webapps/ROOT.war_
