### ISSUE TITLE
Kaui 2.0.11 does not work with Killbill latest image

### ISSUE THREAD

**Issue by KBbitsP** [killbill/killbill-cloud#247]
Issue : I used the below docker compose file : 

```
version: '3.2'
volumes:
  db:
services:
  killbill:
    image: killbill/killbill:latest
    ports:
      - "8080:8080"
    environment:
      - KILLBILL_DAO_URL=jdbc:mysql://db:3306/killbill
      - KILLBILL_DAO_USER=root
      - KILLBILL_DAO_PASSWORD=killbill
      - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
  kaui:
    image: killbill/kaui:2.0.11
    ports:
      - "9090:8080"
    environment:
      - KAUI_CONFIG_DAO_URL=jdbc:mysql://db:3306/kaui
      - KAUI_CONFIG_DAO_USER=root
      - KAUI_CONFIG_DAO_PASSWORD=killbill
      - KAUI_KILLBILL_URL=http://killbill:8080
  db:
    image: killbill/mariadb:0.24
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=killbill
```

The installation goes fine and Kaui login page appears fine. But after entering username and password it says Killbill is not available. 

However, it seems to work fine if I change the killbill image to 0.24.0 in place of latest. 

The same has also been reported by another user, attaching the kaui.out file.
[kaui.out.log](https://github.com/killbill/killbill-cloud/files/12112216/kaui.out.log)
