### ISSUE TITLE
kpm diagnostic tool behaves inconsistently when the api credentials are specified in a config file as well as on the command line

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-cloud#269]
Steps to reproduce:

1. Create a `config.yml` file as follows:

```
killbill:
  api_key: bob
  api_secret: lazar
  port: 8080
  host: localhost
  user: admin
  password: password
  plugins_dir: /var/tmp/bundles
```

2. Run the kpm diagnostic command as follows:

```
kpm diagnostic --account-export=<account id from bob/lazar tenant> --config_file=config.yml --killbill-api-credentials=t1 t1 
```

3. In this case, the diagnostic file contains tenant information from the `t1/t1` tenant and account information from the `bob/lazar` tenant. 

**Expected Behavior:** We should disallow specifying both a config file and command line options to prevent such inconsistent behavior.
