### ISSUE TITLE
Problems enabling Plugins (Stripe)

### ISSUE THREAD

**Issue by adamlc** [killbill/killbill-cloud#28]
Hi all, im currently evaluating killbill and testing with the docker guide. Everything has been fine so far, but I got to the point where I wanted to test Stripe. I followed the guide, add the ENV var, setup stripe.yml etc and started up KB. When I try to create a new payment method I get the following:

```json
{
  "className": "org.killbill.billing.payment.api.PaymentApiException",
  "code": 7028,
  "message": "Payment plugin killbill-stripe is not registered",
  "causeClassName": null,
  "causeMessage": null,
  "stackTrace": []
}
```

Investigating further I noticed something in the logs that may help?

```
2016-01-08 11:24:06,100 [localhost-startStop-1] WARN  o.k.b.osgi.pluginconf.PluginFinder - File non existent: Skipping parsing of plugin_identifiers.json
2016-01-08 11:24:06,101 [localhost-startStop-1] WARN  o.k.b.osgi.pluginconf.PluginFinder - Configuration root dir /var/lib/killbill/bundles/plugins/ruby is not a valid directory
2016-01-08 11:24:06,101 [localhost-startStop-1] WARN  o.k.b.osgi.pluginconf.PluginFinder - Configuration root dir /var/lib/killbill/bundles/plugins/java is not a valid directory
2016-01-08 11:24:06,102 [localhost-startStop-1] WARN  o.k.b.osgi.pluginconf.PluginFinder - File non existent: Skipping parsing of plugin_identifiers.json
2016-01-08 11:24:06,102 [localhost-startStop-1] WARN  o.k.b.osgi.pluginconf.PluginFinder - Configuration root dir /var/lib/killbill/bundles/plugins/ruby is not a valid directory
2016-01-08 11:24:06,102 [localhost-startStop-1] WARN  o.k.b.osgi.pluginconf.PluginFinder - Configuration root dir /var/lib/killbill/bundles/plugins/java is not a valid directory
```

I tried to create the missing directories and restart the server, but I got the following instead:

```
2016-01-08 11:35:40,615 [localhost-startStop-1] WARN  o.k.b.osgi.pluginconf.PluginFinder - File non existent: Skipping parsing of plugin_identifiers.json
2016-01-08 11:35:40,616 [localhost-startStop-1] WARN  o.k.b.osgi.pluginconf.PluginFinder - File non existent: Skipping parsing of plugin_identifiers.json
```

So it looks like some directories and files are missing? I'm using the image ```killbill/killbill:0.16.0```.

If you need any further logs please let me know :smiley:

**Comment by adamlc** [comment]
Don't know if this helps (i'm still new :wink: ), but it looks like the KPM file generated OK:

```yaml
killbill:
  group_id:
  artifact_id:
  version: 0.16.0
  default_bundles_version:
  jvm: -server -Djava.security.egd=file:/dev/./urandom -XX:PermSize=512m -XX:MaxPermSize=1G -Xms1G -Xmx2G -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=12345 -XX:+CMSClassUnloadingEnabled -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -Xloggc:/var/log/tomcat7/gc.log -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintTenuringDistribution -Dorg.killbill.server.properties=file:///etc/killbill/killbill.properties -Dlogback.configurationFile=/etc/killbill/logback.xml
  nexus:
    ssl_verify: false
    url: https://oss.sonatype.org
    repository: releases
  plugins:
    java:
    - group_id: org.kill-bill.billing.plugin.java
      artifact_id: analytics-plugin
      packaging: jar
      classifier:
      version: 3.0.0
    ruby:
    - group_id: org.kill-bill.billing.plugin.ruby
      artifact_id: stripe-plugin
      packaging: tar.gz
      classifier:
      version: 3.0.0
  plugins_dir: /var/lib/killbill/bundles
  properties:
    com.sun.management.jmxremote: true
    com.sun.management.jmxremote.authenticate: false
    com.sun.management.jmxremote.port: 8000
    com.sun.management.jmxremote.ssl: false
    java.rmi.server.hostname: $(hostname).$(hostname -d)
    java.security.egd: file:/dev/./urandom
    jruby.compile.invokedynamic: false
    logback.configurationFile: /etc/killbill/logback.xml
    net.sf.ehcache.skipUpdateCheck: true
    org.killbill.billing.osgi.bundles.jruby.conf.dir: /etc/killbill
    org.killbill.billing.osgi.dao.url: jdbc:mysql://dbserver:3306/killbill_0_16_0
    org.killbill.billing.osgi.dao.user: root
    org.killbill.billing.osgi.dao.password: root
    org.killbill.dao.url: jdbc:mysql://dbserver:3306/killbill_0_16_0
    org.killbill.dao.user: root
    org.killbill.dao.password: root
    org.killbill.jruby.context.scope: THREADSAFE
    org.killbill.metrics.graphite: false
    org.killbill.metrics.graphite.host: localhost
    org.killbill.metrics.graphite.port: 2003
    org.killbill.notificationq.analytics.historyTableName: analytics_notifications_history
    org.killbill.notificationq.analytics.tableName: analytics_notifications
    org.killbill.osgi.bundle.install.dir: /var/lib/killbill/bundles
    org.killbill.osgi.root.dir: /var/lib/killbill/felix-cache
    org.killbill.server.baseUrl: http://localhost:8080
    org.killbill.server.properties: file:///etc/killbill/killbill.properties
    org.killbill.server.http.gzip: true
    org.killbill.security.shiroResourcePath: classpath:shiro.ini
    org.killbill.server.test.mode: true
  webapp_path: /var/lib/tomcat7/webapps/ROOT.war
```
